githubConfigUrl: https://github.com/robandpdx-auto
githubConfigSecret: arc-robandpdx-auto
maxRunners: 16
minRunners: 8
runnerScaleSetName: "self-hosted"
runnerGroup: "self-hosted"
containerMode:
  type: "dind"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/robandpdx/actions-runner:2.332.0
        command: ["/home/runner/run.sh"]
