githubConfigUrl: https://github.com/robandpdx-admin-ops
githubConfigSecret: arc-robandpdx-admin-ops
maxRunners: 1
minRunners: 1
runnerScaleSetName: "issue-runner"
runnerGroup: "issue-runner"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/robandpdx/actions-runner:2.331.0
        command: ["/home/runner/run.sh"]